apiVersion: apps/v1
kind: Deployment
metadata:
  name: houses
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mosaik-houses
  template:
    metadata:
      labels:
        app: mosaik-houses
    spec:
      containers:
      - name: houses
        image: mosaik/backend_houses:dev
        ports:
        - containerPort: 8080