apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-mosaik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosaik
  template:
    metadata:
      labels:
        app: mosaik
    spec:
      containers:
      - name: postgresql-mosaik
        image: postgresql-mosaik:dev
        ports:
        - containerPort: 5432