apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mosaik-users
  template:
    metadata:
      labels:
        app: mosaik-users
    spec:
      containers:
      - name: users
        image: mosaik/backend_users:dev
        ports:
        - containerPort: 8080